# Starts from the project_root_dir in utils.path_utils
output_dirs:
  root: calculations/keep1
  data: data
  figures: figures

# Starts from the data_root_dir in data_loader
sonic_data_dir: SonicData/select_fields

only_plots: False

calculations:
  w_avg:
    enabled: True
    only_plot: False
    y_label: "Average Vertical Windspeed (m/s)"
  T_avg:
    enabled: True
    y_label: "Average Temperature (degC)"
    only_plot: False