# Starts from the project_root_dir in utils.path_utils
output_dirs:
  root: calculations/keep2
  data: data
  figures: figures

# Starts from the data_root_dir in data_loader
sonic_data_dir: SonicData/select_fields

only_plots: False

calculations:
  w_avg:
    enabled: False
    only_plot: False
    y_label: "Average Vertical Windspeed (m/s)"
  speed_avg:
    enabled: False
    only_plot: False
    y_label: "Average Horizontal Windspeed (m/s)"
  u_avg:
    enabled: False
    only_plot: False
    y_label: "Average U (m/s)"
  v_avg:
    enabled: False
    only_plot: False
    y_label: "Average V (m/s)"
  dir_avg:
    enabled: True
    only_plot: False
    y_label: "Average Direction (degrees from North)"
  T_avg:
    enabled: True
    y_label: "Average Temperature (degC)"
    only_plot: False